W7D5/Gheddit/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users
  resource :session, only: [:new,:create,:destroy]
  # get '/session/destroy'
  resources :subs do
    member do
      resources :posts, only:[:new]
    end
  end

  resources :posts, except: [:index,:new] do
    member do
      resources :comments, only:[:new]
    end
  end
end

W7D5/Gheddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :bigint           not null, primary key
#  username      :string           not null
#  pw_digest     :string           not null
#  session_token :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class User < ApplicationRecord
    attr_reader :password 

    validates :username, :session_token, presence: true, uniqueness: true
    validates :pw_digest, presence: true

    after_initialize :ensure_session_token


    ## This validation checks pw length on save, nil is allowed so we can pull from db 
    ## without error. Requires @password to be set at same time as pw_digest
    validates :password, length:{minimum: 6}, allow_nil: true

    ####################Associations######################################
    
    has_many :subs, foreign_key: :moderator_id, class_name: :Sub 
    has_many :posts, foreign_key: :author_id, class_name: :Post 
    ####################Auth Methods##################################

    def self.find_by_credentials(username,pass)
        user = User.find_by(username: username)

        if user and user.password=(pass)
            return user 
        else
            return nil
        end

    end

    def password=(pass)
        @password = pass 
        self.pw_digest = BCrypt::Password.create(pass)
    end

    def is_password?(pass)
        BCrypt::Password.new(pw_digest).is_password?(pass)
        #create a new Bcrypt Password instance from the pw digest and call its 
        #own is_password? method to check. 
    end

    def make_session_token
        SecureRandom.urlsafe_base64
    end

    def reset_session_token!
        #must reset session_token and save to db
        self.session_token = make_session_token
        self.save!
        #return session token so we can leverage this to set
        #session[:session_token] at the same time
        self.session_token
    end

    def ensure_session_token
        #to be called upon instantiation
        self.session_token ||= make_session_token
    end

    #######################################################################

end

W7D5/Gheddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
    
   

    def index
        render :index 
    end

    def new
        # @user = User.new(user_params)
        render :new
    end

    def create
        # debugger
        @user = User.new(user_params)
        @user.password = params[:user][:password]
        # debugger 
        if @user.save
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            @user.pw_digest = nil 
            render :new 
        end
    end

   

    def show
        @user = User.find(params[:id])
    end

    def destroy
        user = User.find(params[:id])
        user.destroy 
        render :index 
    end
end

W7D5/Gheddit/app/helpers/users_helper.rb
module UsersHelper
end

W7D5/Gheddit/app/views/users/index.html.erb
<h1>All Users</h1>

<% User.all.each do |user| %>

    <h2><%= user.username %></h2>

<% end %>

W7D5/Gheddit/app/views/users/new.html.erb
<h1>Create an Account</h1>

<form action="<%= users_url%>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

    <label for=""> Username
        <input type="text" name="user[username]">
    </label>

     <label for=""> Password
        <input type="text" name="user[password]">
    </label>

    <input type="submit" value="Sign Up">

</form>

<% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <h2><%= error %></h2>
    <% end %>
<% end %>

W7D5/Gheddit/app/views/users/show.html.erb
<h1> <%= @user.username %> </h1>

<h2> My Subs </h2>
<form action="<%=new_sub_url%>" method="GET">
        <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
        <input type="submit" value="Create New">
    </form>

<% @user.subs.each do |sub| %>

    <h3> <%= sub.title  %> </h3>
    <form action="<%=sub_url(sub)%>" method="GET">
        <input type="submit" value="Go!">
    </form>

    <form action="<%= edit_sub_url(sub) %>" method="GET">
           
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <input type="submit" value="Edit Sub">
    </form>

      <form action="<%= sub_url(sub) %>" method="POST">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
            <input type="submit" value="Delete Sub">
    </form>
<% end %>

<br>
<br>
<br>

<form action="<%=user_url(@user) %>" method="POST">
    <input type="hidden" name="_method" value="delete">
    <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">
    <input type="submit" value="Delete User">

</form>